name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: mutation testing

    steps:
      - uses: actions/checkout@v2

      - name: gradle clean pitest
        uses: eskatos/gradle-command-action@v2.2.0
        with:
          arguments: clean pitest
