name: CI

on:
  # Triggers the workflow on push or pull request events not only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: mutation testing

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: gradle clean pitest
        # You may pin to the exact commit or the version.
        uses: eskatos/gradle-command-action@v2.1.5
        with:
          # Path to the Gradle Wrapper directory
          #wrapper-directory: # optional
          # Path to the Gradle executable
          #gradle-executable: # optional
          # Gradle version to use
          #gradle-version: # optional
          # Path to the root directory of the build
          #build-root-directory: # optional
          # Gradle command line arguments, see gradle --help
          arguments: clean pitest
          # Whether caching wrapper installation is enabled or not, default to 'true'
          #wrapper-cache-enabled: # optional
          # Whether caching dependencies is enabled or not, default to 'false'
          #dependencies-cache-enabled: # optional
          # Globs of files to hash in the build root directory, separated by new lines, use best-effort if unset
          #dependencies-cache-key: # optional
          # Whether to restore only if exact match, default to 'false'
          #dependencies-cache-exact: # optional
          # Whether caching build configuration is enabled or not, default to 'false'
          #configuration-cache-enabled: # optional
          # Globs of files to hash in the build root directory, separated by new lines, use best-effort if unset
          #configuration-cache-key: # optional
          # Whether to restore only if exact match, default to 'false'
          #configuration-cache-exact: # optional
