name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    name: mutation testing

    steps:
      - uses: actions/checkout@v2

      - name: gradle clean pitest
        uses: eskatos/gradle-command-action@v2.2.1
        with:
          arguments: clean pitest

      - name: Generate test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Test Results
          files: ./**/build/test-results/TEST-*.xml
