name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: read
  checks: write

jobs:
  run-pitest:
    runs-on: ubuntu-latest
    name: mutation testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup gradle and execute pitest
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check pitest
          cache-disabled: true

      - name: Upload PIT report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: PITEST Mutation Test Report
          path: build/reports/pitest

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: build/reports/tests

      - name: Generate test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results
          files: ./**/build/test-results/test/TEST-*.xml

      - name: Generate PIT report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: PIT Results
          files: ./**/build/reports/pitest/mutations.xml
